on: [push, pull_request]
name: Test
permissions:
  contents: read

jobs:
  version-matrix:
    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.20", "1.21", "1.22", "1.23"]
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Configure known hosts
        if: matrix.platform != 'ubuntu-latest'
        run: |
          mkdir -p  ~/.ssh
          ssh-keyscan -H github.com > ~/.ssh/known_hosts

      - name: Set Git config
        run: |
          git config --global user.email "gha@example.com"
          git config --global user.name "GitHub Actions"

      - name: Test
        run: make test-coverage
